POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "João Lisboa",
    "email": "joaolisboa@gmail.com",
    "password": "123456"
}

###

GET http://localhost:3000/users/0827d83a-f592-478c-833d-43f5803429a7

###

GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/34c99f75-0558-4c86-9ff5-7ea95adb107e

###

PUT http://localhost:3000/users/34c99f75-0558-4c86-9ff5-7ea95adb107e
Content-Type: application/json

{
    "name": "Users Teste Updated",
    "email": "usersTesteUpdated@gmail.com"
}

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Produto Teste",
    "description": "Descrição do produto teste",
    "price": 100,
    "categoryId": "f91a6de9-1614-421e-b28b-cbaa7d8f2ba5",
    "stock": 10
}

###

GET http://localhost:3000/products

###

GET http://localhost:3000/products/1

###

GET http://localhost:3000/products/category/1

###

PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Produto Teste Updated",
    "description": "Descrição do produto teste atualizada",
    "price": 150, 
    "categoryId": "1",
    "stock": 15
}

###

DELETE http://localhost:3000/products/1

###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Categoria Teste",
    "description": "Descrição da categoria teste"
}

###

GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/1

###

PUT http://localhost:3000/categories/1
Content-Type: application/json

{
    "name": "Categoria Teste Updated",
    "description": "Descrição da categoria teste atualizada"
}

###

DELETE http://localhost:3000/categories/1



