version: '3.8'
name: api-fastify

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: api-fastify-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LisboaDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
